server:
  port: 8081
  servlet:
    context-path: /outh2

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bcl?serverTimezone=Asia/Shanghai
    username: root
    password: mysql@123
  jpa:
    show-sql: true